
test = require 'batman'

# Local
#builder   = require '../src/cs/builder'
# Global
builder   = require 'builder'

target = builder.target
project = builder.project

test = project('builder', 
	build_dir: './=build'
	staging_dir: './=staging'
	source_dir: './test_src'
)

all = target 'All', ['js/app.js.min']

coffee_files = builder.ls(test.source_dir + '/coffee/*.coffee')
###
target 'js/app.js.min', ['app.js'], ->
	@read()
	console.log('We are the DEEEEEEEEEEEE')
	@minify()
	@write()
	
target 'app.js', ['app.coffee'], ->
	@read()
	@coffee2js()
	@write()
###	

target 'js/app.js.min', ['app.coffee'], ->
	@read()
	@coffee2js()
	@write('js/app.js') # For debugging! :)
	@minify()
	@prependFile('LICENSE')
	@write()
	

target 'app.coffee', coffee_files, ->
	@read()
	@cat()
	@writeTmp()
	

task 'build', 'Build Project', ->
	all.build()
	builder.debug coffee_files
	
task 'test', 'Build Project (test)', ->
	all.build()

